services:
  organisation_service:
    build:
      context: ./organisation_service
    container_name: organisation_service
    networks:
      - green-atom-network
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./organisation_service.db
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  storage_service:
    build:
      context: ./storage_service
    container_name: storage_service
    networks:
      - green-atom-network
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./storage_service.db
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  nginx:
    image: nginx_green_atom:latest
    build: ./nginx
    container_name: green_atom_nginx
    ports:
      - "80:80"
    networks:
      - green-atom-network
    depends_on:
      - organisation_service
      - storage_service
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'

  rabbitmq:
    image: "rabbitmq:3-management"
    networks:
      - green-atom-network
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 15s
      timeout: 30s
      retries: 10

networks:
  green-atom-network:
    driver: bridge
