version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: waste_accounting
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  organization_service:
    build: ./organization_service
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_HOST: rabbitmq

  storage_service:
    build: ./storage_service
    ports:
      - "8001:8001"
    environment:
      RABBITMQ_HOST: rabbitmq
