name: Test Coverage Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r organization_service/requirements.txt
          pip install -r storage_service/requirements.txt
          pip install pytest pytest-cov coverage

      - name: Run organization_service tests with coverage
        run: |
          pytest organization_service/tests --cov=organization_service --cov-report=xml:organization_service/coverage.xml

      - name: Run storage_service tests with coverage
        run: |
          pytest storage_service/tests --cov=storage_service --cov-report=xml:storage_service/coverage.xml

      - name: Ensure coverage reports exist
        run: |
          ls -l organization_service/coverage.xml storage_service/coverage.xml

      - name: Combine coverage reports
        run: |
          coverage combine organization_service/coverage.xml storage_service/coverage.xml || echo "Coverage combine failed, skipping"

      - name: Generate final coverage report
        run: |
          coverage report -m > coverage.txt
          coverage xml -o coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: $GITHUB_WORKSPACE/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
