name: Test Coverage Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r organisation_service/requirements/requirements.txt -r storage_service/requirements/requirements.txt -r organisation_service/requirements/requirements.test.txt -r storage_service/requirements/requirements.test.txt

      - name: Run organisation_service tests with coverage
        run: |
          COVERAGE_FILE=.coverage_organization coverage run --concurrency=gevent -m pytest organisation_service/tests

      - name: Run storage_service tests with coverage
        run: |
          COVERAGE_FILE=.coverage_storage coverage run --concurrency=gevent -m pytest storage_service/tests

      - name: Generate combined coverage report
        run: |
          coverage combine .coverage_organization .coverage_storage
          coverage xml -o coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: "coverage.xml"
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: "Neizvestnyj/green_atom"
