name: Test Coverage Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r organization_service/requirements.txt -r storage_service/requirements.txt -r requirements-test.txt

      - name: Run organization_service tests with coverage
        run: |
          pytest organization_service/tests --cov=organization_service --cov-report=xml:organization_service/coverage.xml --cov-report=term-missing

      - name: Run storage_service tests with coverage
        run: |
          pytest storage_service/tests --cov=storage_service --cov-report=xml:storage_service/coverage.xml --cov-report=term-missing

      - name: Combine coverage reports
        run: |
          coverage combine organization_service/coverage.xml storage_service/coverage.xml || echo "Coverage combine failed, skipping"

      - name: Generate final coverage report
        run: |
          coverage report -m > coverage.txt
          coverage xml -o coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: "${{ github.workspace }}/coverage.xml"
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: "Neizvestnyj/green_atom"
